name: pandora-ci

on:
  push:
    branches:
      - "godot-4.x"
    paths-ignore:
      - "**.jpg"
      - "**.png"
      - "**.svg"
      - "**.md"
      - "**plugin.cfg"
  pull_request:
    paths-ignore:
      - "**.jpg"
      - "**.png"
      - "**.svg"
      - "**.md"
      - "**plugin.cfg"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    timeout-minutes: 5

    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        godot-version: ["4.2.2", "4.3"]

    name: "🤖 CI on Godot ${{ matrix.godot-version }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Runner Tracking ID to prevent orphan processes
        run: |
          export RUNNER_TRACKING_ID=""

      - name: Run GDUnit4 tests
        uses: MikeSchulze/gdUnit4-action@v1.1.1
        with:
          godot-version: ${{ matrix.godot-version }}
          godot-status: "stable"
          timeout: 3
          paths: "res://test"
          version: "installed"
          publish-report: false
          report-name: report_Godot${{ matrix.godot-version }}_unit-tests

  finalize:
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    name: "Final Results"
    needs: [unit-tests]
    steps:
      - run: exit 1
        if: >-
          ${{
                 contains(needs.*.result, 'failure')
              || contains(needs.*.result, 'cancelled')
          }}
